name: ackify-ce

services:
  ackify-migrate:
    image: btouchard/ackify-ce
    container_name: ackify-ce-migrate
    environment:
      APP_BASE_URL: "${APP_BASE_URL}"
      APP_ORGANISATION: "${APP_ORGANISATION}"
      OAUTH_PROVIDER: "${OAUTH_PROVIDER}"
      OAUTH_CLIENT_ID: "${OAUTH_CLIENT_ID}"
      OAUTH_CLIENT_SECRET: "${OAUTH_CLIENT_SECRET}"
      DB_DSN: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ackify-db:5432/${POSTGRES_DB}?sslmode=disable"
    depends_on:
      ackify-db:
        condition: service_healthy
    networks:
      - internal
    command: ["/app/migrate", "up"]
    entrypoint: []
    restart: "no"

  ackify-ce:
    image: btouchard/ackify-ce
    container_name: ackify-ce
    restart: unless-stopped
    environment:
      APP_BASE_URL: "https://${APP_DNS}"
      APP_ORGANISATION: "${APP_ORGANISATION}"
      OAUTH_PROVIDER: "${OAUTH_PROVIDER}"
      OAUTH_CLIENT_ID: "${OAUTH_CLIENT_ID}"
      OAUTH_CLIENT_SECRET: "${OAUTH_CLIENT_SECRET}"
      OAUTH_ALLOWED_DOMAIN: "${OAUTH_ALLOWED_DOMAIN}"
      OAUTH_COOKIE_SECRET: "${OAUTH_COOKIE_SECRET}"
      DB_DSN: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ackify-db:5432/${POSTGRES_DB}?sslmode=disable"
      ED25519_PRIVATE_KEY_B64: "${ED25519_PRIVATE_KEY_B64}"
      LISTEN_ADDR: ":8080"
    depends_on:
      ackify-migrate:
        condition: service_completed_successfully
      ackify-db:
        condition: service_healthy
    networks:
      - internal
    ports:
      - "8080:8080"

  ackify-db:
    image: postgres:16-alpine
    container_name: ackify-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ackify_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  internal:

volumes:
  ackify_data:
